apiVersion: v1
kind: Template
labels:
  template: search-api-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: search-api template
    description: |-
      This is a template for search-api.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: search-api-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Defines how to build the application
    labels:
      app: search-api
      template: master-build-pipeline
    name: search-api
    namespace: ${namespacePrefix}-tools
  spec:
    completionDeadlineSeconds: 1800
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: search-api:latest
    postCommit: {}
    resources:
      limits:
        cpu: "4"
        memory: 4Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: Serial
    source:
      git:
        ref: master
        uri: https://github.com/bcgov/fams3
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: DOTNET_STARTUP_PROJECT
          value: app/SearchApi/SearchApi.Web/SearchApi.Web.csproj
        - name: DOTNET_ASSEMBLY_NAME
        - name: DOTNET_NPM_TOOLS
        - name: DOTNET_TEST_PROJECTS
        - name: DOTNET_CONFIGURATION
          value: Release
        - name: DOTNET_RESTORE_SOURCES
        - name: DOTNET_PACK
          value: "true"
        - name: DOTNET_TOOLS
        - name: DOTNET_INCREMENTAL
          value: "true"
        - name: DOTNET_RESTORE_CONFIGFILE
          value: src/NuGet.config
        - name: NEXUS_REPO_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: nexus-config
        - name: NEXUS_REPO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: nexus-config
        - name: NEXUS_REPO_URL
          valueFrom:
            secretKeyRef:
              key: url
              name: nexus-config
        - name: NEXUS_REPO_API_KEY
          valueFrom:
            secretKeyRef:
              key: password
              name: fams3-nuget-local
        from:
          kind: ImageStreamTag
          name: dotnet:3.1
          namespace: ${namespacePrefix}-tools
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers: []
