apiVersion: v1
kind: Template
labels:
  template: file-adapter-template
message: |-
  A Jenkins server must be instantiated in this project to manage
  the Pipeline BuildConfig created by this template. You will be able to log in to
  it using your OpenShift user credentials.
metadata:
  annotations:
    openshift.io/display-name: file-adapter template
    description: |-
      This is a template for file-adapter.
    iconClass: icon-jenkins
    tags: instant-app,jenkins
  name: file-adapter-template
parameters:
- description: The OpenShift Namespace prefix.
  displayName: Namespace Prefix (Prefix for each namespace ie prefix-tools, prefix-dev etc)
  name: namespacePrefix
  required: true
  value:
- description: Data partner service name.
  displayName: Name of the data partner service
  name: dataPartnerService
  required: true
  value:
- name: TAG
  required: true
  value: dev
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${dataPartnerService}-file-adapter
    name: ${dataPartnerService}-file-adapter
  spec:
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      io.kompose.service: ${dataPartnerService}-file-adapter
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: ${dataPartnerService}-file-adapter
      spec:
        containers:
          - env:
            - name: JAEGER_SERVICE_NAME
              value: ${dataPartnerService}-file-adapter
            - name: DATA_PARTNER
              value: ${dataPartnerService}
            envFrom:
            - secretRef:
                name: ${dataPartnerService}-file-adapter-config
            - secretRef:
                name: rabbit-mq-configuration
            - secretRef:
                name: aspnet-env
            - secretRef:
                name: jeager-config
            - secretRef:
                name: splunk-config
            image: ''
            imagePullPolicy: IfNotPresent
            name: ${dataPartnerService}-file-adapter
            ports:
            - containerPort: 8080
              protocol: TCP
            resources:
              limits:
                cpu: 250m
                memory: 1Gi
              requests:
                cpu: 100m
                memory: 256Mi
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            volumeMounts:
              - mountPath: /app/.ssh/keys/
                name: ssh-key
                readOnly: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - name: ssh-key
          secret:
            defaultMode: 420
            secretName: fams3-jca-private-key
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${dataPartnerService}-file-adapter
        from:
          kind: ImageStreamTag
          name: ${dataPartnerService}-file-adapter:${TAG}
          namespace: ${namespacePrefix}-tools
      type: ImageChange
